(in-package #:iup/cffi)

(include "iup/iup.h")

(cenum (:iup-action :base-type :int)
	((:ignore "IUP_IGNORE"))
	((:default "IUP_DEFAULT"))
	((:close "IUP_CLOSE"))
	((:continue "IUP_CONTINUE")))

(cenum (:iup-status :base-type :int)
	((:error "IUP_ERROR"))
	((:no-error "IUP_NOERROR"))
	((:opened "IUP_OPENED"))
	((:invalid "IUP_INVALID"))
	((:invalid-id "IUP_INVALID_ID")))

(cenum (:iup-record-mode :base-type :int)
	((:binary "IUP_RECBINARY"))
	((:text "IUP_RECTEXT")))

(cenum (:iup-position :base-type :int)
	((:left "IUP_LEFT"))
	((:top "IUP_TOP"))
	((:center "IUP_CENTER"))
	((:right "IUP_RIGHT"))
	((:bottom "IUP_BOTTOM"))
	((:mouse "IUP_MOUSEPOS"))
	((:center-parent "IUP_CENTERPARENT"))
	((:current "IUP_CURRENT")))

(cenum (:iup-show-state :base-type :int)
	((:show "IUP_SHOW"))
	((:restore "IUP_RESTORE"))
	((:minimize "IUP_MINIMIZE"))
	((:maximize "IUP_MAXIMIZE"))
	((:hide "IUP_HIDE")))

(cenum (:iup-scroll-op :base-type :int)
	((:up "IUP_SBUP"))
	((:down "IUP_SBDN"))
	((:page-up "IUP_SBPGUP"))
	((:page-down "IUP_SBPGDN"))
	((:vertical-positioning "IUP_SBPOSV"))
	((:vertical-drag "IUP_SBDRAGV"))
	((:left "IUP_SBLEFT"))
	((:right "IUP_SBRIGHT"))
	((:page-left "IUP_SBPGLEFT"))
	((:page-right "IUP_SBPGRIGHT"))
	((:horizontal-positioning "IUP_SBPOSH"))
	((:horizontal-drag "IUP_SBDRAGH")))

(cenum (:iup-mouse-button :base-type :char)
  ((:button1 "IUP_BUTTON1"))
  ((:button2 "IUP_BUTTON2"))
  ((:button3 "IUP_BUTTON3"))
  ((:button4 "IUP_BUTTON4"))
  ((:button5 "IUP_BUTTON5")))
